### ISSUE TITLE
Example mod out of date

### ISSUE THREAD

**Issue by gdude2002** [CrimsonDawn45/Fabric-Shield-Lib-Example-Mod#1]
Might be worth updating the example mod, as it's pretty much the only form of documentation you've got.

Could also do with adding some resources, since it isn't clear where things should be or what they should be named from the source that's in here.

**Comment by CrimsonDawn45** [comment]
Yeah, sorry this project kinda got abandoned I'm pretty busy with college and all but I'm going to try to get some stuff updated and see if I can get some stuff fixed soon.

**Comment by CrimsonDawn45** [comment]
I updated the example mod to the latest version.
